"""cgate: middleware and CLI between AI assistants and managed servers."""

from __future__ import annotations

try:
    from cgate._version import __version__ as __version__
except ImportError:
    # _version.py is generated by hatch-vcs (for source installs) and by
    # scripts/_ensure_version.py (for PyInstaller binaries). When neither
    # has run yet (e.g., a bare `python -c "import cgate"` from a fresh
    # clone), fall back to git describe so the runtime version is still
    # meaningful instead of crashing with a hard-coded stale value.
    import subprocess
    from pathlib import Path

    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0", "--match=v*"],
            cwd=Path(__file__).resolve().parents[2],
            capture_output=True,
            text=True,
            check=True,
        )
        __version__ = result.stdout.strip().lstrip("v")
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        __version__ = "0.0.0+unknown"
